/*
 * PANGEA License Manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"flag"
	"fmt"
	"log"

	sw "github.com/vaefremov/pnglic/openapi"
	"github.com/vaefremov/pnglic/server"
)

var configPath = flag.String("c", "./pnglic_config.yaml", "Path to config file")
var writeConfigToFile = flag.Bool("x", false, "Generate config file filled with default parameters")

func main() {
	flag.Parse()
	conf := server.NewConfig(*configPath)
	conf.Report()
	if *writeConfigToFile {
		if err := conf.Write(*configPath); err != nil {
			log.Printf("Warning: %s", err.Error())
		}
	}
	router := sw.NewRouter(conf)

	log.Fatal(router.Run(fmt.Sprintf(":%d", conf.Port)))
}
