/*
 * PANGEA License Manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"flag"
	"fmt"
	"log"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "github.com/vaefremov/pnglic/openapi"
)

var port = flag.Int("p", 9995, "port to start server on")
var dsnPtr = flag.String("dsn", "/Users/efremov/Projects/LIC/PNGLicenseManager/Backend/licset.sqlite", "Path to sqlite3 database")

func main() {
	flag.Parse()
	log.Printf("Server starting on port ", *port)

	router := sw.NewRouter(*dsnPtr)

	log.Fatal(router.Run(fmt.Sprintf(":%d", *port)))
}
