/*
 * PANGEA License Manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

// LicenseFile - Get license file by client id and timestamp of issue
func LicenseFile(c *gin.Context) {
	LicenseFileImpl(c)
}

// LicensedFeaturesForKey - Returns list of all license features related to a given key
func LicensedFeaturesForKey(c *gin.Context) {
	LicensedFeaturesForKeyImpl(c)
}

// ListClients - Returns list of all organizations related to licensation
func ListClients(c *gin.Context) {
	ListClientsImpl(c)
}

// ListFeatures - Returns list of features
func ListFeatures(c *gin.Context) {
	ListFeaturesImpl(c)
}

// ListHistoryItems - Returns list of all issues if license files to the specified client
func ListHistoryItems(c *gin.Context) {
	ListHistoryItemsImpl(c)
}

// ListKeys - Returns general list of keys
func ListKeys(c *gin.Context) {
	ListKeysImpl(c)
}

// Ping - Return the backend version, DB version, additional info
func Ping(c *gin.Context) {
	PingImpl(c)
}

// PackageContent - Returns list of features belonging to the specified package
func PackageContent(c *gin.Context) {
	PackageContentImpl(c)
}
