/*
 * PANGEA License Manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

// CreateKey - Creates a new key and assigns it to the specified client
func CreateKey(c *gin.Context) {
	CreateKeyImpl(c)
}

// HistoryLicenseFile - Get license file by client id and timestamp of issue
func HistoryLicenseFile(c *gin.Context) {
	HistoryLicenseFileImpl(c)
}

// LicensedFeaturesForKey - Returns list of all license features related to a given key
func LicensedFeaturesForKey(c *gin.Context) {
	LicensedFeaturesForKeyImpl(c)
}

// ListClients - Returns list of all organizations related to licensation
func ListClients(c *gin.Context) {
	ListClientsImpl(c)
}

// ListFeatures - Returns list of features
func ListFeatures(c *gin.Context) {
	ListFeaturesImpl(c)
}

// ListHistoryItems - Returns list of all issues if license files to the specified client
func ListHistoryItems(c *gin.Context) {
	ListHistoryItemsImpl(c)
}

// ListKeys - Returns general list of keys
func ListKeys(c *gin.Context) {
	ListKeysImpl(c)
}

// MakeLicenseFile - Generate license file from the current set of licenses related to key ID and store it in the history
func MakeLicenseFile(c *gin.Context) {
	MakeLicenseFileImpl(c)
}

// Ping - Return the backend version, DB version, additional info
func Ping(c *gin.Context) {
	PingImpl(c)
}

// PackageContent - Returns list of features belonging to the specified package
func PackageContent(c *gin.Context) {
	PackageContentImpl(c)
}

// ProlongLicensedFeaturesForKey - Update license features for the given key ID, replace the previousely defined ones
func ProlongLicensedFeaturesForKey(c *gin.Context) {
	ProlongLicensedFeaturesForKeyImpl(c)
}

// UpdateLicensedFeaturesForKey - Update license features for the given key ID, replace the previousely defined ones
func UpdateLicensedFeaturesForKey(c *gin.Context) {
	UpdateLicensedFeaturesForKeyImpl(c)
}
