/*
 * PANGEA License Manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PingOk struct {

	BackVersion string `json:"backVersion"`

	DbVersion string `json:"dbVersion"`
}
